name: catan_randomizer
version: 1.0.0
dependencies:
  angular: "1.1.2"
  web_components: "0.10.1"
  browser: ">=0.10.0+2 <0.11.0"
  sass: any
dev_dependencies:
  mock: ">=0.11.0+2 <0.12.0"
  mockito: "^0.10.1"
  test: '>=0.12.0 <0.13.0'
transformers:
- angular:
    html_file:
      - lib/component/catan_board/catan_board.html
      - lib/component/catan_hex/catan_hex.html
- sass